[theme]

# The preset Streamlit theme that your custom theme inherits from. One of "light" or "dark".
base = "dark"

# Primary accent color for interactive elements.
primaryColor="#27a5da"

# Background color for the main content area.
backgroundColor="#f7fbfd"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor="#d6dcde"

# Color used for almost all text.
textColor="#171b29"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
#font =